### ISSUE TITLE
Does anyone care about or maintain this repository? 

### ISSUE THREAD

**Issue by Grana2codes** [PacktPublishing/Mastering-Python-Networking-Fourth-Edition#2]
The topology labs don't build because the yaml files are wrong, I've taken the time to correct them as much as I could and submitted a pull request over a month ago which has been ignored. This is frankly unacceptable for a book that was published only just this year. If the intention is that readers/students follow along with the lab, then the repository should be maintained. I can't recommend this book to anyone in the current state of this repository if the CML lab doesn't even build.

**Comment by ericchou1** [comment]
Sorry about the delay @Grana2codes! This issue was raised in https://members.networkautomation.community/ a few months ago and I merge the PR. Thank you again for your work and investment in the issue. I really appreciate it.

**Comment by ericchou1** [comment]
Closing the issue per PR merge.
